In [3]:
import pandas as pd
import numpy as np
df_test=pd.read_excel(r"C:\Users\Mahmood\Downloads\data\realme.      .xlsx")
df_test

,BRAND,Model,RAM,Storage,Condition,FIX,display,display kind,cpu,Price
0,realme,Realme C51,4,64,2,0,6.74,ips lcd,Unisoc T612,3600
1,realme,Realme C51,4,128,3,0,6.74,ips lcd,Unisoc T612,4700
2,realme,Realme C51,6,128,4,0,6.74,ips lcd,Unisoc T612,6150
3,realme,Realme C51,8,128,4,0,6.74,ips lcd,Unisoc T612,6900
4,realme,Realme C53,4,128,2,0,6.74,ips lcd,Unisoc T612,4300
...,...,...,...,...,...,...,...,...,...,...
418,Honor,X8b,8,256,1,0,6.7,AMOLED,Snapdragon 685,5000
419,Honor,X7b,8,128,3,0,6.8,IPS LCD,Snapdragon 685,6000
420,Honor,Magic 5 Pro,12,256,1,0,6.81,LTPO OLED,Snapdragon 8 Gen 2,13000
421,Honor,Honor 90,8,256,3,0,6.7,AMOLED,Snapdragon 7 Gen 1,11500
422,Honor,Honor 200,12,512,4,0,6.7,OLED,Snapdragon 7 Gen 3,20000

In [4]:
df_test=df_test[["BRAND","Model","RAM","Storage","Condition","FIX","Price"]]
df_test.head(2)

    BRAND       Model  RAM  Storage  Condition  FIX Price
0  realme  Realme C51    4       64          2    0  3600
1  realme  Realme C51    4      128          3    0  4700

In [ ]:
from sklearn.preprocessing import LabelEncoder
# تحويل كل القيم في عمود Model ل string
df_test['Model'] = df_test['Model'].astype(str)

#هنعمل دلوقتي LabelEncoder 
le_model = LabelEncoder()
df_test['Model_encoded'] = le_model.fit_transform(df_test['Model'])


print(df_test[['Model', 'Model_encoded']].head())

        Model  Model_encoded
0  Realme C51             65
1  Realme C51             65
2  Realme C51             65
3  Realme C51             65
4  Realme C53             66

C:\Users\Mahmood\AppData\Local\Temp\ipykernel_8528\1412442441.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['Model'] = df_test['Model'].astype(str)
C:\Users\Mahmood\AppData\Local\Temp\ipykernel_8528\1412442441.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['Model_encoded'] = le_model.fit_transform(df_test['Model'])

In [ ]:
# إنشاء الديكشنري النهائي للـ GUI
brand_model_mapping = {}

for index, row in df_test.iterrows():
    # دمج البراند مع الموديل (مثلاً: Samsung + S23 Ultra)
    full_name = f"{row['BRAND']} {row['Model']}"
    
    # إضافة الاسم كـ Key والكود كـ Value
    brand_model_mapping[full_name] = row['Model_encoded']

# عرض أول 10 عناصر للتأكد
print("النتائج النهائية للديكشنري (الاسم الكامل : الكود):")
for name, code in list(brand_model_mapping.items())[:10]:
    print(f"{name} -> {code}")

النتائج النهائية للديكشنري (الاسم الكامل : الكود):
realme Realme C51 -> 65
realme Realme C53 -> 66
realme Realme C55 -> 67
realme Realme Narzo 60x 5G -> 77
realme Realme Narzo 60 5G -> 75
realme Realme Narzo 60 Pro 5G -> 76
realme Realme 11 4G -> 56
realme Realme 11x 5G -> 58
realme Realme 11 Pro+ 5G -> 57
realme Realme GT Neo5 SE -> 74

In [ ]:
brand_model_mapping
# هو دا dict اللي محتاجينه عشان GUI بعدين

{'realme Realme C51': 65,
 'realme Realme C53': 66,
 'realme Realme C55': 67,
 'realme Realme Narzo 60x 5G': 77,
 'realme Realme Narzo 60 5G': 75,
 'realme Realme Narzo 60 Pro 5G': 76,
 'realme Realme 11 4G': 56,
 'realme Realme 11x 5G': 58,
 'realme Realme 11 Pro+ 5G': 57,
 'realme Realme GT Neo5 SE': 74,
 'realme Realme C61': 68,
 'realme Realme C63': 69,
 'realme Realme C65 4G': 70,
 'realme Realme C65 5G': 71,
 'realme Realme C67': 72,
 'realme Realme Narzo N65 5G': 80,
 'realme Realme Narzo 70x 5G': 79,
 'realme Realme Narzo 70 Pro 5G': 78,
 'realme Realme 12+ 5G': 59,
 'realme Realme 13+ 5G': 61,
 'realme Realme 13 Pro+ 5G': 60,
 'realme Realme GT 6T': 73,
 'realme Realme 14 Pro 5G': 62,
 'realme Realme 14 Pro+ 5G': 63,
 'realme Realme 16 5G': 64,
 'samsung Samsung Galaxy A14': 104,
 'samsung Samsung Galaxy A24': 108,
 'samsung Samsung Galaxy A34 5G': 111,
 'samsung Samsung Galaxy A54 5G': 114,
 'samsung Samsung Galaxy S23': 120,
 'samsung Samsung Galaxy S23+': 123,
 'samsung Samsung Galaxy S23 Ultra': 122,
 'samsung Samsung Galaxy S23 FE': 121,
 'samsung Samsung Galaxy Z Flip5': 136,
 'samsung Samsung Galaxy Z Fold5': 139,
 'samsung Samsung Galaxy A15': 105,
 'samsung Samsung Galaxy A15 5G': 106,
 'samsung Samsung Galaxy A25 5G': 109,
 'samsung Samsung Galaxy A35 5G': 112,
 'samsung Samsung Galaxy A55 5G': 115,
 'samsung Samsung Galaxy S24': 124,
 'samsung Samsung Galaxy S24+': 127,
 'samsung Samsung Galaxy S24 Ultra': 126,
 'samsung Samsung Galaxy S24 FE': 125,
 'samsung Samsung Galaxy Z Flip6': 137,
 'samsung Samsung Galaxy Z Fold6': 140,
 'samsung Samsung Galaxy A26 5G': 110,
 'samsung Samsung Galaxy A36 5G': 113,
 'samsung Samsung Galaxy A56 5G': 116,
 'samsung Samsung Galaxy S25': 128,
 'samsung Samsung Galaxy S25+': 132,
 'samsung Samsung Galaxy S25 Ultra': 131,
 'samsung Samsung Galaxy S25 Edge': 129,
 'samsung Samsung Galaxy S25 FE': 130,
 'samsung Samsung Galaxy S26': 133,
 'samsung Samsung Galaxy S26+': 135,
 'samsung Samsung Galaxy S26 Ultra': 134,
 'samsung Samsung Galaxy Z Flip7': 138,
 'samsung Samsung Galaxy A06': 103,
 'samsung Samsung Galaxy A16 5G': 107,
 'samsung Samsung Galaxy M15 5G': 117,
 'samsung Samsung Galaxy M35 5G': 118,
 'samsung Samsung Galaxy M55 5G': 119,
 'samsung Samsung Galaxy Z Fold7': 141,
 'google Pixel 9 Pro Fold': 41,
 'google Pixel 10 Pro Fold': 31,
 'google Pixel 7 Pro ': 37,
 'google pixel 6a': 159,
 'google pixel 3xl': 156,
 'google Pixel 9 Pro XL ': 42,
 'google pixel 3': 154,
 'google pixel 6': 158,
 'google pixel 3a': 155,
 'google Pixel 8a': 40,
 'google Pixel 4': 34,
 'google Pixel 7': 36,
 'google Pixel 6 Pro': 35,
 'google Pixel 7a': 38,
 'google pixel 4xl': 157,
 'google Pixel 10 Pro XL': 32,
 'google pixel 7 pro': 160,
 'google pixel 7a': 161,
 'google Pixel 10\xa0': 33,
 'google Pixel 8 Pro': 39,
 'XIAOMI Redmi note 14': 97,
 'XIAOMI Redmi note 14 pro plus 5G': 99,
 'XIAOMI 17 Ultra': 12,
 'XIAOMI Mix Fold 4': 30,
 'XIAOMI 14 Ultra': 5,
 'XIAOMI Redmi note 14 pro': 98,
 'XIAOMI Redmi note 15 pro 5G': 101,
 'XIAOMI Redmi note 15 pro 4G': 100,
 'XIAOMI Redmi 15C': 87,
 'XIAOMI Redmi 14C': 85,
 'XIAOMI Redmi 13C': 84,
 'XIAOMI Redmi note 15 pro plus 5G': 102,
 'XIAOMI Redmi Note 13\xa0': 95,
 'XIAOMI Redmi Note 13 Pro Plus 5G': 94,
 'XIAOMI Redmi Note 15\xa0': 96,
 'XIAOMI 15T': 10,
 'XIAOMI 14T pro': 7,
 'XIAOMI Redmi 15': 86,
 'XIAOMI Poco X7': 54,
 'XIAOMI Poco X7 pro': 55,
 'XIAOMI Poco F7': 47,
 'XIAOMI Poco F7 pro': 48,
 'XIAOMI 15T Pro': 11,
 'XIAOMI 15': 8,
 'XIAOMI 15 ultra': 9,
 'XIAOMI Poco M6 Pro': 49,
 'XIAOMI Poco X6': 52,
 'XIAOMI Poco X6 pro': 53,
 'XIAOMI Poco F6': 45,
 'XIAOMI Poco F6 Pro': 46,
 'XIAOMI Redmi A3': 88,
 'XIAOMI Redmi 13': 83,
 'XIAOMI Redmi Note 13 Pro 4G': 92,
 'XIAOMI Redmi Note 13 Pro 5G': 93,
 'XIAOMI 14T': 6,
 'XIAOMI 14': 3,
 'XIAOMI 14 Pro': 4,
 'XIAOMI Poco X5': 50,
 'XIAOMI Poco X5 Pro': 51,
 'XIAOMI Poco F5': 43,
 'XIAOMI Poco F5 Pro': 44,
 'XIAOMI Redmi 12C': 82,
 'XIAOMI Redmi 12': 81,
 'XIAOMI Redmi Note 12S': 91,
 'XIAOMI Redmi Note 12 4G': 89,
 'XIAOMI Redmi Note 12 Pro': 90,
 'XIAOMI 13T pro': 2,
 'XIAOMI 13': 0,
 'XIAOMI 13 ultra': 1,
 'Honor Magic 7 Pro': 27,
 'Honor Magic 7': 26,
 'Honor Honor 400 Pro': 18,
 'Honor Honor 400': 17,
 'Honor X9c': 153,
 'Honor X8c': 150,
 'Honor X7c': 147,
 'Honor Magic 6 Pro': 25,
 'Honor Honor 200 Pro': 15,
 'Honor Honor 200': 13,
 'Honor Magic V3': 29,
 'Honor X9b': 152,
 'Honor X8b': 149,
 'Honor X7b': 146,
 'Honor Magic 5 Pro': 23,
 'Honor Honor 90': 19,
 'Honor X9a': 151,
 'Honor Honor 90 Smart': 21,
 'Honor Honor 200 Smart': 16,
 'Honor Magic 6 Lite': 24,
 'Honor Magic 5 Lite': 22,
 'Honor Magic V2': 28,
 'Honor Honor 200 Lite': 14,
 'Honor Honor 90 Lite': 20,
 'Honor X8a': 148,
 'Honor X7a': 145,
 'Honor X6a': 142,
 'Honor X6b': 143,
 'Honor X6c': 144}

In [ ]:
df_test=pd.get_dummies(df_test,columns=["BRAND"],dtype=int)    #عملنا one hot encoding لي brand
df_test.head()

,Model,RAM,Storage,Condition,FIX,Price,Model_encoded,BRAND_Honor,BRAND_XIAOMI,BRAND_google,BRAND_realme,BRAND_samsung
0,Realme C51,4,64,2,0,3600,65,0,0,0,1,0
1,Realme C51,4,128,3,0,4700,65,0,0,0,1,0
2,Realme C51,6,128,4,0,6150,65,0,0,0,1,0
3,Realme C51,8,128,4,0,6900,65,0,0,0,1,0
4,Realme C53,4,128,2,0,4300,66,0,0,0,1,0

In [ ]:
df_test.head(5)
#وكدا وصلنا اننا ننضف الداتا و جاهزه تدخل لي مودل machine learning

,Model,RAM,Storage,Condition,FIX,Price,Model_encoded,BRAND_Honor,BRAND_XIAOMI,BRAND_google,BRAND_realme,BRAND_samsung
0,Realme C51,4,64,2,0,3600,65,0,0,0,1,0
1,Realme C51,4,128,3,0,4700,65,0,0,0,1,0
2,Realme C51,6,128,4,0,6150,65,0,0,0,1,0
3,Realme C51,8,128,4,0,6900,65,0,0,0,1,0
4,Realme C53,4,128,2,0,4300,66,0,0,0,1,0